development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:cef830e7e0b62b7e7159a2608186d559@scat.redistogo.com:11527/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: Tripnotes_6_production
