default: &default # adapter: sqlite3
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # database: storage/development.sqlite3
  database: <%= Rails.application.credentials.DB_NAME.dev_db %>
  username: <%= Rails.application.credentials.DB_USERNAME.dev_db %>
  password: <%= Rails.application.credentials.DB_PASSWORD.dev_db %>

test:
  <<: *default
  database: tripnotes_test

